name: opaf
description: "Open Pattern Format (OPAF) library for parsing and compiling pattern files."
version: 0.3.0
homepage: https://github.com/open-pattern-format/opaf-dart
topics:
  - opaf
  - parser

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  expressions: ^0.2.5+2
  image: ^4.5.4
  path: ^1.9.1
  string_validator: ^1.2.0
  uuid: ^4.5.1
  version: ^3.0.0
  xml: ^6.5.0

dev_dependencies:
  args: ^2.7.0
  lints: ^6.0.0
